[package]
name = "lawbook"
version = "0.0.0"
publish = ["crates-io"]
edition = "2024"
rust-version = "1.88"
description = "lawbook command-line tool"
authors = ["Drew Simmons <dsimmo14@gmail.com>"]
license = "MIT"
repository ="https://github.com/drew-simmons/lawbook"
homepage = "https://drew-simmons.github.io/lawbook/"
documentation = "https://drew-simmons.github.io/lawbook/"
readme = "README.md"
keywords = ["cli"]
categories = ["command-line-utilities"]
exclude = ["/docs", "/.github"]

[package.metadata.dist]
dist = true

[dependencies]
anyhow = "1"
clap = { version = "4.6.6", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

# The profile that dist uses for release artifacts.
[profile.dist]
inherits = "release"
lto = "thin"
